### ISSUE TITLE
Compatible with Flurry 6.0.0 and MoPub 3.11.0?

### ISSUE THREAD

**Issue by joeykrim** [flurry/FlurryAdapterForMoPubAndroid#1]
MoPub 3.11.0: https://github.com/mopub/mopub-android-sdk

**Comment by ugonna** [comment]
Yes, the current version of this adapter works with Flurry 6.0.0 and MoPub 3.11.0. Did you face any particular issues using the adapter with those libraries?

**Comment by joeykrim** [comment]
Yes, receiving error code 20 and contacted support@flurry.com.
Unsure whether the issue is related to a Flurry Dashboard configuration error message I'm receiving, "Error creating Gemini mappings, you may have trouble receiving ads. Please retry save later" when I create a Native Ad space or related to a code implementation issue.

**Comment by joeykrim** [comment]
Flurry support confirmed a system issue that has now been resolved.

New issue:
09-20 12:42:39.747  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Fetching Flurry Native Ad now.
09-20 12:42:42.911  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ onFetched(com.flurry.android.ads.FlurryAdNative@434ba138) Successful.
09-20 12:42:42.911  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ FlurryForwardingNativeAd onFetched: Native Ad fetched successfully! com.flurry.android.ads.FlurryAdNative@434ba138
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad main image found.
09-20 12:42:42.921  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ Flurry Native Ad icon image found.
09-20 12:42:42.931  23403-23552/joeykrim E/Volley﹕ [7633] NetworkDispatcher.run: Unhandled exception java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
    java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
            at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
            at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
            at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
            at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:42.931  23403-23550/joeykrim E/Volley﹕ [7631] NetworkDispatcher.run: Unhandled exception java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
    java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
            at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
            at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
            at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
            at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:43.031  23403-23403/joeykrim D/MoPub﹕ Failed to download a native ads image:
    com.mopub.volley.VolleyError: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:141)
     Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
            at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
            at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
            at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
            at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
09-20 12:42:43.031  23403-23403/joeykrim D/FlurryForwardingNativeAd﹕ preCacheImages: Unable to cache Ad image. Error[Unable to download images associated with ad.]
09-20 12:42:43.031  23403-23403/joeykrim D/MoPub﹕ Failed to download a native ads image:
    com.mopub.volley.VolleyError: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:141)
     Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
            at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:152)
            at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:162)
            at com.mopub.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
            at com.mopub.network.RequestQueueHttpStack.performRequest(RequestQueueHttpStack.java:52)
            at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
            at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

**Comment by joeykrim** [comment]
Due to no response above, opened a separate issue: https://github.com/flurry/FlurryAdapterForMoPubAndroid/issues/3
