### ISSUE TITLE
java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by Luklek** [flurry/FlurryAdapterForMoPubAndroid#14]
I am trying to use native video ads with
.videoViewId(R.id.native_video_view) 
Is native_video_view the id of my main image (1200px x 627px) in the native ad layout?
I get the error below:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                 Process: com.kkkeyboard.emoji.keyboard.theme.ShadingPink, PID: 17392
                                                                                                 java.lang.ClassCastException: android.support.v7.widget.AppCompatImageView cannot be cast to android.view.ViewGroup
                                                                                                     at com.mopub.nativeads.FlurryNativeAdRenderer$FlurryNativeViewHolder.fromViewBinder(FlurryNativeAdRenderer.java:96)
                                                                                                     at com.mopub.nativeads.FlurryNativeAdRenderer.renderAdView(FlurryNativeAdRenderer.java:40)
                                                                                                     at com.mopub.nativeads.FlurryNativeAdRenderer.renderAdView(FlurryNativeAdRenderer.java:14)

**Comment by ugonna** [comment]
Hi, @Luklek. `native_video_view` has to be a `ViewGroup`. `AppCompatImageView` is a regular `View`.

**Comment by Luklek** [comment]
Thanks for your reply.
Is there any demo app code to show a full example of integration of Flurry video native ads (with MoPub adapter)?

By the way, there is a typo in the readme here:
final FlurryNativeAdRenderer flurryRenderer = new Flurry**Natqive**AdRenderer(flurryBinder);

**Comment by ugonna** [comment]
There is no demo app, but snippets showing the Flurry-related parts of the integration are in the README. You can also look into MoPub's sample app to learn more about native video integration. 

If you have any integration questions, please email integration [AT] flurry {dot} com and we'll be happy to work through your integration.
